### ISSUE TITLE
Add a formal LICENSE

### ISSUE THREAD

**Issue by yuchi** [Yomguithereal/react-blessed#1]
This code is very interesting, and looking at your *package.json* looks like you’re releasing it under the MIT license.

Could you please state it in the *README* and add a proper *LICENSE* file?

**Comment by Yomguithereal** [comment]
Hello @yuchi. I will do so as soon as I have some time to wrap up a first releasable version of the lib.

**Comment by Yomguithereal** [comment]
I added the LICENSE. Are you the person working on `react-titanium` @yuchi?

**Comment by yuchi** [comment]
Yes I am! I stole most of the infrastructure from this module, and I wanted to be in line with your interests.

Do you mind if I place you and this project on the acknowledgements?

**Comment by Yomguithereal** [comment]
I don't mind at all @yuchi. Please come back here if you hit issues with custom rendering so we can fix it together.
