### ISSUE TITLE
readme shows incredible demo, but checked in demo missing rich content

### ISSUE THREAD

**Issue by cdaringe** [Yomguithereal/react-blessed#106]
thanks for this library, very cool.

# problem

blessed is giving me a hard time. in trying to replicate layouts and events as shown in the readme, i want to consult how it was done by the author

# discussion

the demo is missing all of the _key_ details. for example, `<Jobs />` is more or less empty. is there a _rich_ example available?

**Comment by Yomguithereal** [comment]
Hello @cdaringe. The example shown by the readme's gif stands [here](https://github.com/medialab/sandcrawler-dashboard). But be aware that it was made on a rather ancient version of the lib. Else I remember that there exists some react-blessed version of SQL db uis somewhere that could help you find rich examples.

**Comment by cdaringe** [comment]
Awesome thank you!
