### ISSUE TITLE
falsy text is not rendered

### ISSUE THREAD

**Issue by mizchi** [Yomguithereal/react-blessed#12]
```
<box top='center' >{0}</box>
```

is not rendered

**Comment by Yomguithereal** [comment]
Hello @mizchi. I will check that asap.

**Comment by yuchi** [comment]
I *believe* this is expected behavior to support conditional children: `{ value && <Something /> }`.

**Comment by Yomguithereal** [comment]
@yuchi, upon trying it on React's [frontpage](http://facebook.github.io/react/) it does work and renders `0`. I guess it will only avoid other falsy values.

**Comment by yuchi** [comment]
Sorry, my bad.

**Comment by Yomguithereal** [comment]
This behavior is kinda weird anyway.

**Comment by Yomguithereal** [comment]
This should be fixed by now. Will soon release a `0.0.3`.

**Comment by mizchi** [comment]
:+1:
