### ISSUE TITLE
Drop ReactBlessedTextComponent if really not useful anymore

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/react-blessed#13]

**Comment by yuchi** [comment]
I still have it lingering in the repo but it's completely unused for me.

**Comment by Yomguithereal** [comment]
Same for me now. It will probably disappear soon.

**Comment by Yomguithereal** [comment]
On a side note, if you drop the injection, does it cause any issue? Just wondering if I need to keep a noop class for the TextComponent.

**Comment by yuchi** [comment]
I am **currently** [not injecting it](https://github.com/yuchi/react-titanium/blob/9851281c6806cafe73f34946c8217a0d501bdfa9/src/ReactTitaniumInjection.js). But I sometimes got issues with text components rendered as `<span id=".nodeblahblahblah">my text</span>` because of it.

Looks like 0.14 still has an awful lot of references to the DOM.

**Comment by yuchi** [comment]
Non reproducible anymore. I have to admin the renderer was in a bad state at that moment though.

The bug-triggerer looked like this

```js
class Something extends Component {
  render() {
    const { ...children, props } = this.props;
    return (
      <SomethingElse {{ ...props }}>
        { children }
      </SomethingElse>
    );
  }
}
```

Notice how I confused `{ children, ...props }` with `{ ...children, props }`. I was using a keyed object as a child, therefore having the object values as children.

**Comment by Yomguithereal** [comment]
@yuchi, you confirm that I can drop the TextComponent?

**Comment by yuchi** [comment]
![3064513_orig](https://cloud.githubusercontent.com/assets/646609/9687904/58b7cd8e-532c-11e5-9061-7f63289b1875.png)

> Drop it like it’s hot…
> Drop it like it’s hot… 
> Drop it like it’s hot…

**Comment by Yomguithereal** [comment]
Thanks for the laugh @yuchi! I am clearly hearing the soundtrack.

**Comment by yuchi** [comment]
I just noticed that you’re [using lodash to operate on children](https://github.com/Yomguithereal/react-blessed/blob/master/src/ReactBlessedComponent.js#L70).

My I suggest you to switch to a less performant but guaranteed form that uses `React.Children.*` methods? (See [mine](https://github.com/yuchi/react-titanium/blob/master/src/utils/separateChildren.js))

**Comment by jdalton** [comment]
:full_moon_with_face:

**Comment by yuchi** [comment]
I'm sorry @jdalton, didn't mean to offend lodash! :)

Technically speaking react children are an opaque data structure that can be composed of arrays, objects, arrays of object of elements, single elements. Actually I don't know the whole spectrum and cases, that's why I use that react util.

**Comment by Yomguithereal** [comment]
I see your point about `ReactChildren.map` as it would probably be future-proof @yuchi, but I just cannot hurt @jdalton's feeling like that. Let me solve this soon :).

**Comment by jdalton** [comment]
Lol :heart:
