### ISSUE TITLE
Can't get <terminal> to work

### ISSUE THREAD

**Issue by nmn** [Yomguithereal/react-blessed#29]
trying to render a <terminal> doesn't work.

Also, I would love the code behind the demo being shown in the gif. I'm trying to build a simple dashboard like utility that will run multiple watch commands and show them side-by-side.

My first big problem is that all the text rendered by react-blessed is currently white. I'm not sure how to make colors from the output of various commands show up.

Second, I would like to use the <terminal> element from blessed sometimes, and that doesn't seem to work either.

Lastly, I'm still having trouble making any box scrollable. Any help on one or more of these issues will be very helpful. Thanks!

(Also React-blessed is amazing. Thanks for your work)

**Comment by Yomguithereal** [comment]
Hello @nmn.
The code running the thingy shown in the gif is [here](https://github.com/medialab/sandcrawler-dashboard/tree/react/src) and is actually a dashboard for the [sandcrawler](http://medialab.github.io/sandcrawler/) spiders.

Concerning your output colors, are you using ANSI escape characters? If so, normally they should be rendered correctly. If you are using blessed color tags, be sure to pass a prop `tags` to true on the relevant blessed elements.

> Second, I would like to use the element from blessed sometimes, and that doesn't seem to work either.

I am not sure I understand you there, can you develop a bit more, please?

Concerning the scrollable part, isn't the `scrollable` prop not working for you?
Be sure to check blessed's [tests](https://github.com/chjj/blessed/tree/master/test) to see some fine examples.

Anyway, is your code available somewhere so I can help you better?

**Comment by nmn** [comment]
Sorry, typo in my issue, I tried using the `terminal` widget, but that errors out.
As for colors, ANSI escape characters don't seem to be working for me.

In any case, I'm gonna take a look at the sand crawler app and see if I can learn something.

**Comment by Yomguithereal** [comment]
Let me check that more thoroughly tomorrow. I guess you are working on [this](https://github.com/nmn/multi-command) project?

**Comment by Yomguithereal** [comment]
Any update on this @nmn?
