### ISSUE TITLE
label styling isn't working

### ISSUE THREAD

**Issue by patrickkettner** [Yomguithereal/react-blessed#33]
with blessed, I am able to set the color for the label's style inline, e.g.

```js
var box = blessed.box({
  label: ' {blue-fg}Prompt{/blue-fg} ',
  border: {
    type: 'line'
  }
  }
});
```

But when I try to do the same from react-blessed, it just includes the style declarations as is, inside of the label itself

![image](https://cloud.githubusercontent.com/assets/465414/11486734/c547ae9c-976f-11e5-9abe-2afb816c7a15.png)

Is there any way to style the label's color?

**Comment by Yomguithereal** [comment]
Hello @patrickkettner.
If I record correctly, `blessed` introduced the `tags` boolean on boxes not too long ago (I guess it's for perf reasons). And I think you know have to explicitly declare that you want tags to be rendered. Can you try to add a `tags` prop to your element rendered with `react-blessed` and tell me whether this solves it?

**Comment by patrickkettner** [comment]
well dang, I don't know how I missed that

Thank you so much for the fast response - that fixed it!
