### ISSUE TITLE
props in constructor does not match props in render

### ISSUE THREAD

**Issue by dbkaplun** [Yomguithereal/react-blessed#44]
Expected:
```
constructor { foo: 'bar' }
render { foo: 'bar' }
```
Actual:
```
constructor { foo: 'bar' }
render {}
```
Code:
```js
import _ from 'lodash'
import React, {Component} from 'react'
import blessed from 'blessed'
import {render} from 'react-blessed'

export default class PropsExample extends Component {
  constructor (props) {
    super(_.merge({foo: 'bar'}, props))
    console.log('constructor', this.props)
  }
  render () {
    console.log('render', this.props)
    return (
      <box
        top="center"
        left="center"
        width="50%"
        height="50%"
        border={{type: 'line'}}
        style={{border: {fg: 'blue'}}}>
        Hello World!
      </box>
    )
  }
}

var screen = new blessed.Screen()
screen.key('C-q', () => { process.exit() })
render(<PropsExample />, screen)
```

**Comment by Yomguithereal** [comment]
Hello @dbkaplun. This seems to be a tough one. Can you guarantee me that this would work with `react-dom` please?

**Comment by yuchi** [comment]
Also are you sure that you don’t want to use default props?

```js
class PropsExample extends Component {
  // …Nothing required here…
}

PropsExample.defaultProps = {
  foo: 'bar'
};
```

**Comment by dbkaplun** [comment]
Looks like `react-dom` exhibits the same behavior: http://jsbin.com/gutagazaxa/1/edit?html,js,output

I've filed facebook/react#5772, maybe the React guys will have some insight.

**Comment by yuchi** [comment]
I **believe** you’re not supposed to mutate or change what you pass from your constructor to the one from Component.

**Comment by Yomguithereal** [comment]
That's probably the case indeed but this is really counter-intuitive.

**Comment by yuchi** [comment]
That’s because the props are always replaced from the outside. If you think about it it‘s pretty obvious it doesn’t work, but still looks *strange*.

The main issue is that you **think** that `super(props)` create the object that will be diffed against, which is false!

**Comment by dbkaplun** [comment]
facebook/react#5772
  
> dbkaplun commented 9 hours ago
> @zpao I guess I'm still a little unclear.. are you saying this.props in the constructor intentionally has a different value than this.props in render()? Thanks in advance

> jimfb commented 9 hours ago
> @dbkaplun Correct - The this.props is passed into the constructor as a convince for easy access within the constructor. The component's props are controlled by React, not by the constructor, for the reasons discussed in #5320.
