### ISSUE TITLE
Add example in vanilla Javascript

### ISSUE THREAD

**Issue by piranna** [Yomguithereal/react-blessed#49]
Example are written in `jsx`, and compiled result is imposible to understand. Please add a simple demo in vanilla Node.js javascript to show how it can be used the library, and if possible how to define templates to set the elements too.

**Comment by Yomguithereal** [comment]
Hello @piranna. I see your point and agree but unfortunately I don't have much time to do so. I'll gladly accept a PR though :). Else I'll tackle this point when migrating to react v15.

**Comment by piranna** [comment]
Thank you :-) I've been reading a bit about jsx and seems to be vanilla Javascript with support for React tags, but still it confuse me a lot :-P

**Comment by konobi** [comment]
you could have a look at JSnoX as an example of doing react with plain JS.

**Comment by revolunet** [comment]
closable ?
