### ISSUE TITLE
Checkbox does not update checked state

### ISSUE THREAD

**Issue by dundalek** [Yomguithereal/react-blessed#56]
For example in this repro case checkbox stays unchecked:

```js
import React, {Component} from 'react';
import blessed from 'blessed';
import {render} from 'react-blessed';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      checked: false
    };
  }

  componentDidMount() {
    setTimeout(() => this.setState({ checked: true }), 10);
  }

  render() {
    return <checkbox checked={this.state.checked} />;
  }
}

const screen = blessed.screen();

screen.key(['escape', 'q', 'C-c'], function(ch, key) {
  return process.exit(0);
});

render(<App />, screen);
```

From my understading adding `checked` into `RAW_ATTRIBUTES` should fix the issue.

As a workaround for now I use `<checkbox value={this.state.checked}>` and monkeypatch blessed:
```js
blessed.widget.checkbox.prototype.setValue = function(value) {
  if (value) {
    this.check();
  } else {
    this.uncheck();
  }
}
```

**Comment by Yomguithereal** [comment]
Its absence from `RAW_ATTRIBUTES` seems to be the problem indeed @dundalek. I'll accept a PR to fix it if you have time to create it. What's more, I reckon the way `RAW_ATTRIBUTES` are checked is really not efficient and should be done using a `Set`. I'll be really glad if you could add this improvement to a PR also :)

**Comment by dundalek** [comment]
Sounds good, I'll give it a try.
