### ISSUE TITLE
Can't get mouse events to work

### ISSUE THREAD

**Issue by gaearon** [Yomguithereal/react-blessed#6]
I'm probably missing something obvious but I can't seem to add `onPress={this.handlePress}` to boxes—they don't respond.

**Comment by Yomguithereal** [comment]
Hello @gaearon. Will check that asap to see if I didn't forget something.

**Comment by Yomguithereal** [comment]
Ok, so after some investigation it seems that mouse events don't work with OSX's basic terminal ([source](https://github.com/chjj/blessed/issues/2)). However, keyboard inputs work but you should set either the `input` or the `keyable` property of your box to `true`.

On a side note, if I remember correctly, the `press` event (not `keypress`) is reserved for blessed buttons only so it won't work on a standard box.

**Comment by chjj** [comment]
Yeah, Terminal.app does not support mouse events without a [plugin][1]. @dbkaplun explains how here: https://github.com/slap-editor/slap-Terminal.app-profile

iTerm2 supports mouse events but also has its own shortcomings (e.g. combining characters will actually break the layout of any program. they've neglected to fix this for a long time now).

Personally, if I were using OSX as my primary OS, I'd start a headless X server and just use xterm or urxvt. But I have serious terminal biases.

[1]: https://bitheap.org/mouseterm/

**Comment by Yomguithereal** [comment]
Are there still problems here @gaearon?

**Comment by gaearon** [comment]
I suppose not!

**Comment by chentsulin** [comment]
Maybe we should add this into Readme? I also try this for a while...

**Comment by Yomguithereal** [comment]
@chentsulin this is an issue with blessed, not with the react renderer. However, it would surely be a good thing indeed to create such thing as a FAQ section on this documentation or a disclaimer about such common traps. Let me check where we could place it.
