### ISSUE TITLE
How to receive all childs keypress events?

### ISSUE THREAD

**Issue by steve-chavez** [Yomguithereal/react-blessed#61]
On blessed is possible to do this with: 
```js
box.on('element keypress', () => {});
```

Instead of ```on('keypress')``` I have a root element that needs to handle this, I've tried with ```onElementKeypress``` but it doesn''t work. Check [blessed event bubbling](https://github.com/chjj/blessed#event-bubbling).

**Comment by Yomguithereal** [comment]
For this kind of advanced use case I guess you should probably use refs and bind your event. It would be a bit difficult for the library to guess the combination of event elements based on the name (not saying it can't be done, just that maybe it should not be done). But maybe some middle way can be found. Something along `onCustom` taking a tuple of `[event, handler]` or even a list of those.

**Comment by malonehedges** [comment]
@steve-chavez any luck figuring out child keypress events? Struggling with the best way to do this.

**Comment by steve-chavez** [comment]
What I did was to have a ref to a root `<element>` like [this](https://github.com/subzerocloud/subzero-cli/blob/master/src/dashboard.jsx#L275) then bind the `element keypress` event in a `componentDidMount` like [this](https://github.com/subzerocloud/subzero-cli/blob/master/src/dashboard.jsx#L63).

**Comment by malonehedges** [comment]
@steve-chavez Thanks so much for the reply! I'll try that out.
