### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by devsnek** [Yomguithereal/react-blessed#66]
I'm not sure what is going on here, but any help would be appreciated.

My intention is `Clyde#0001 BOT`

![](https://gc.gy/⟡.png)

**Comment by Yomguithereal** [comment]
The result is strange indeed. But it might come from the fact that blessed boxes have absolute positions which means that your two boxes overlap and that you need to position them explicitly. There should be blessed primitives more suited to your use case.
