### ISSUE TITLE
Question: in the samples, from which module is "box" being imported?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Yomguithereal/react-blessed#74]
In the samples I see code snippets like this:
```js
class Jobs extends Component {
  render() {
    return <box label="Jobs"
                class={stylesheet.bordered}
                left="60%"
                width="40%"
                height="60%" />;
  }
}
```
But I don't see where is this `box` element is imported from. I can't import statements for it, any hints?

**Comment by Yomguithereal** [comment]
Hello @Zaid-Ajaj. `box` is not imported because it is a blessed primitive node, the same way you don't import `div` when using `react-dom`. If you want to know which primitive there are, check blessed docs about widgets [here](https://github.com/chjj/blessed#widgets).

**Comment by Zaid-Ajaj** [comment]
Thanks for quick answer! I think I understand now. I was planning on making this library work with [Fable](fable.io) and when we usually use third-party react components, we import them explicitly from a module, for the case of `div`, we import it using the `createElement` function i.e. 
```fs
let div props children = createElement "div" props children
```
So I was wondering if we could explicitly import the element from somewhere to make this bridge work

**Comment by Yomguithereal** [comment]
I guess you can do the exact same thing thusly:

```f#
let box props children = createElement "box" props children
```

**Comment by Zaid-Ajaj** [comment]
@Yomguithereal That makes sense, I will try it :smile: thanks a lot
