### ISSUE TITLE
Replacing react dependency by using babel transforms

### ISSUE THREAD

**Issue by SirWindfield** [Yomguithereal/react-blessed#76]
Hey!

Would it be (generally speaking) possible to replace React with the babel-transform-jsx plugin? As far as I understood, react-blessed uses React under the hood, at runtime. This sounds like a huge dependency for just a cli app. [Ink](https://github.com/vadimdemedes/ink) for example uses the transform approach, transpiling JSX at compile time to normal function calls. 

I am not sure how much reward one would get compared to the time needed to port.

**Comment by Yomguithereal** [comment]
This can be tried but I am not sure it would work. The runtime works by hooking on some React internals and it might be difficult to drop everything related to it.

**Comment by bensleveritt** [comment]
@SirWindfield As I understand it, the addition of React brings advantages beyond JSX (lifecycle methods, hooks, etc.). It's an overhead, but arguably less worrisome than in the browser.

As there isn't any action here, perhaps this issue can be closed?
