### ISSUE TITLE
Numbers seem to break text nodes

### ISSUE THREAD

**Issue by gaearon** [Yomguithereal/react-blessed#8]
Changing any text node to include a number kills it. (I mean the number type.)  
I think, since it works on web, it should work here too, shouldn't it?

Example:

```js
export default class App extends Component {
  render() {
    return (
      <box label='React Blessed Hot Motion'
           border={{type: 'line'}}
           style={{border: {fg: 'cyan'}}}>
        Hey, {42}
      </box>
    );
  }
}
```

<img width="310" alt="screen shot 2015-08-26 at 14 53 43" src="https://cloud.githubusercontent.com/assets/810438/9492670/46e1b7ae-4c02-11e5-84d8-d8e81f69410b.png">

**Comment by Yomguithereal** [comment]
Hello @gaearon. I guess it's not the number that is problematic but rather the fact that two distinct text nodes are rendered by react. So, since I use a `setContent` on the blessed node twice because I did not take this case into account, only the last one is rendered.

Let me see if I can fix this trivially.

**Comment by yuchi** [comment]
Probably not straightforward. Got issues too and stopped implementing text nodes.

Please, keep me updated :)

**Comment by Yomguithereal** [comment]
Ok, so here my problem is that React text nodes are not aware of their siblings or even of the existence of such siblings which drastically complicates the use of `setContent` for the blessed node. What I could do is use blessed `text` nodes but there isn't such thing as inline nodes in blessed and positioning will be a nightmare to deal with.

I can see another solution working on the id of the text nodes `.1j0tm0peyo0.0.0`, for instance, but this feels somewhat hacky.

**Comment by yuchi** [comment]
`react-titanium` uses a different strategy for final tree composition. The main difference is that while you let every node call `.add` on the parent, I need to get the children **before** the parent is ready ([see here](https://github.com/yuchi/react-titanium/blob/b1da1f26d94d160fbc1adcbe9c6533c5b007e2f4/src/ReactTitaniumComponent.js#L26)) and I was thinking to use that array of children to extract all those that are text nodes, concat them and set them as text.

**Comment by gaearon** [comment]
Does React Native solve / even deal with this?
They use explicit `<Text>` everywhere right?

cc @spicyj @sebmarkbage in case they can share expertise / offer guidance

**Comment by yuchi** [comment]
For me the issues happened when text nodes were treated as normal components and triggered updates that needed to be treated in `ReactComponentEnvironment.processChildrenUpdates`.

**Comment by Yomguithereal** [comment]
@yuchi, I set `ReactComponentEnvironment.processChildrenUpdates` to be a noop to avoid these issues. But it's right that it's problematic not to be able to inject the component environment as the other things. I've not checked whether this particular problem was fixed in `beta3` however.

**Comment by yuchi** [comment]
@Yomguithereal  *ReactEnvironment.Component.inject* still throws in `beta3`

**Comment by spicyj** [comment]
If you want to make this work, you can look at how ReactDOMTextComponent is injected and the code in _updateDOMChildren in ReactDOMComponent.

**Comment by yuchi** [comment]
If *think* I somehow grokked it. Could you please check if I got it wrong, @spicyj?

- both `mountChildren` and `updateChildren` are `ReactMultiChild` APIs, therefore if **I don’t want text elements to fire children updates** I simply need to **not pass them any further**
- if I discern *content* children from *mountables* children in both `mountComponent` and `receiveComponent` I can safely join the resulting values and use them as the final resulting text **without missing any edge or normal case**.

Remember that both in @Yomguithereal’s `react-blessed` and my `react-titanium` we have no concept of mixed nodes and text.

**Comment by spicyj** [comment]
Yes, that should be fine. It gets a little tricky if you support switching between text and other components (not sure if you do) but that sounds correct to me.

**Comment by yuchi** [comment]
That case cannot happen because there would be no way to use a node where text can go.

E.g. in `react-titanium` the `<label>`s cannot have children and has a `text` property.

```xml
<window>
  <label>Some text here</label>
  <!-- becomes -->
  <label text="Some text here" />
</window>
```

In `react-blessed` you only have `node.setContent('Some text here')`.

**Comment by yuchi** [comment]
Actually in Titanium there’s a special case for buttons that can handle children views **alongside** a text property. So no switch can happen.

Great! Thank you @spicyj!

**Comment by Yomguithereal** [comment]
Ok, I fixed this issue by avoiding text components altogether since they are not as relevant in `blessed` as they are for the DOM. I set the content of the blessed node directly in `mountComponent` and `receiveComponent`.
