### ISSUE TITLE
conflict tag name with react declare

### ISSUE THREAD

**Issue by guoshencheng** [Yomguithereal/react-blessed#84]
Hi, is here any support for typescript. i meet a problem.
Use a custom tag should declare namespace JSX. the code may like this

```javascript
declare namespace JSX {
  interface IntrinsicElements {
    'box': any,
    'listtable': any,
  }
}
```
It works fine sometimes but when i use `button`. The tag name is conflict with origin JSX IntrinsicElements definition. any solutions?

**Comment by guoshencheng** [comment]
#85 I have made a pull request to resolve this problem.

**Comment by guoshencheng** [comment]
plan b 
#86

**Comment by cancerberoSgx** [comment]
Hello there, how are you using the library in TypeScript .tsx files ? ,I'm trying with @types/react-blessed , @types/blessed but not success, will keep investigating but would be awesome to have a working example, any tip is most appreciated.

**Comment by danielpza** [comment]
Hello @cancerberoSgx , so did you find a solution, how did you solve it?
